---
title: "David Grubb"
output: html_document
---


828-406-5529

grubbmd@gmail.com

Link to github repository [here](https://github.com/DavidGrubb)


##**What I can offer**

I am hardworking and ambitious. My degree will give me a strong background in Mathematics and I will be able to offer strong critical thinking skills. I conduct myself with the utmost integrity and feel I can be a strong asset to any company. I'm a quick learner, easy to get along with and I will make a good teammate. 

##**Education**

* Major: Bachelor of Science in Mathematics with Business career concentration

* Appalachian State University- December 2018

##**Skills**

* Proficient in Excel

* R programming experience

* Data Entry 

* Sales

* Problem Solving

#####**Relevant courses completed/in progress**
* Marketing and Finance
* Economics and Accounting
* Discrete and Continuous Modeling 
* Data Science 1
* Sports Analytics
* Differential Equations
* Data and Statistical Analysis

##**Experience**

*November 2017-current* **:** Seasonal Package Car Driver and Part-time package handler                           (United Parcel Service)

*March 2016-November 2017* **:** Appliance technician and reconditioned sales                                       (Self Employed) 